nome = input("Qual o seu nome?")
cidade = input ("Qual a sua cidade?")
idade = int(input ("Qual a sua idade?"))
print ("Seu nome é: ", nome)
print ("Sua cidade é: ", cidade)
print ("Sua idade é:", idade)